kind: Deployment
apiVersion: apps/v1
metadata:
  name: myapp-deployment
  namespace: project
  labels:
    app: myapp_dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: cont1
          image: shudhodhan/mycapstone:REPLACE_TAG
          ports:
            - containerPort: 80
