kind: Service
apiVersion: v1
metadata: 
  name: myapp-service
  namespace: project
  labels:
    app: myapp_svc
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008





    